<?php return array (
  'nameToModel' => 
  array (
    'breaks' => 'App\\Models\\Breakk',
    'repairs' => 'App\\Models\\Repair',
    'sales' => 'App\\Models\\Sale',
    'articles' => 'App\\Models\\Article',
    'criteria' => 'App\\Models\\Criterion',
    'messages' => 'App\\Models\\Message',
    'evaluations' => 'App\\Models\\Evaluation',
    'options' => 'App\\Models\\Option',
    'negociations' => 'App\\Models\\Negociation',
    'images' => 'App\\Models\\Image',
    'users' => 'App\\Models\\User',
  ),
  'nameToResource' => 
  array (
    'breaks' => 'App\\Http\\Resources\\BreakResource',
    'repairs' => 'App\\Http\\Resources\\RepairResource',
    'sales' => 'App\\Http\\Resources\\SaleResource',
    'articles' => 'App\\Http\\Resources\\ArticleResource',
    'criteria' => 'App\\Http\\Resources\\CriterionResource',
    'messages' => 'App\\Http\\Resources\\MessageResource',
    'evaluations' => 'App\\Http\\Resources\\EvaluationResource',
    'options' => 'App\\Http\\Resources\\OptionResource',
    'negociations' => 'App\\Http\\Resources\\NegociationResource',
    'images' => 'App\\Http\\Resources\\ImageResource',
    'users' => 'App\\Http\\Resources\\UserResource',
  ),
  'nameToPolicy' => 
  array (
    'repairs' => 'App\\Policies\\RepairPolicy',
    'sales' => 'App\\Policies\\SalePolicy',
    'articles' => 'App\\Policies\\ArticlePolicy',
    'criteria' => 'App\\Policies\\CriterionPolicy',
    'messages' => 'App\\Policies\\MessagePolicy',
    'evaluations' => 'App\\Policies\\EvaluationPolicy',
    'options' => 'App\\Policies\\OptionPolicy',
    'negociations' => 'App\\Policies\\NegociationPolicy',
    'images' => 'App\\Policies\\ImagePolicy',
    'users' => 'App\\Policies\\UserPolicy',
  ),
  'modelToName' => 
  array (
    'App\\Models\\Breakk' => 'breaks',
    'App\\Models\\Repair' => 'repairs',
    'App\\Models\\Sale' => 'sales',
    'App\\Models\\Article' => 'articles',
    'App\\Models\\Criterion' => 'criteria',
    'App\\Models\\Message' => 'messages',
    'App\\Models\\Evaluation' => 'evaluations',
    'App\\Models\\Option' => 'options',
    'App\\Models\\Negociation' => 'negociations',
    'App\\Models\\Image' => 'images',
    'App\\Models\\User' => 'users',
  ),
  'modelToPolicy' => 
  array (
    'App\\Models\\Breakk' => 'App\\Policies\\BreakPolicy',
    'App\\Models\\Repair' => 'App\\Policies\\RepairPolicy',
    'App\\Models\\Sale' => 'App\\Policies\\SalePolicy',
    'App\\Models\\Article' => 'App\\Policies\\ArticlePolicy',
    'App\\Models\\Criterion' => 'App\\Policies\\CriterionPolicy',
    'App\\Models\\Message' => 'App\\Policies\\MessagePolicy',
    'App\\Models\\Evaluation' => 'App\\Policies\\EvaluationPolicy',
    'App\\Models\\Option' => 'App\\Policies\\OptionPolicy',
    'App\\Models\\Negociation' => 'App\\Policies\\NegociationPolicy',
    'App\\Models\\Image' => 'App\\Policies\\ImagePolicy',
    'App\\Models\\User' => 'App\\Policies\\UserPolicy',
  ),
);